name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

jobs:
  harness:
    name: Harness
    permissions:
      contents: read
    uses: aoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoa/eternalist-foundry/.github/workflows/pipeline.yml@f1bb884d4fa2091d517aec9393c64018673bdf13
    with:
      namespace: harness

  witness:
    name: Witness
    permissions:
      contents: read
    uses: aoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoa/eternalist-foundry/.github/workflows/pipeline.yml@f1bb884d4fa2091d517aec9393c64018673bdf13
    with:
      contract: foundry-witness.toml
      namespace: witness
